- hosts: all
  become: true
  tasks:
   - name: install httpd
     apt:
       name: httpd
       state: present
   - name: start and enable httpd
     service:
       name: httpd
       state: started
       enabled: true
